#!/usr/bin/env bash
function amas_refresh {
	root=${1}
	git_ignore="#autogenerated by npm refresh"
	git_ignore="${git_ignore}"$'\n'".gitignore"
	find "${root}" -type f | grep "\-ama$" | sed "s/\(^.*\)-ama$/\1/" | {
		while read ama; do
			git_ignore="${git_ignore}"$'\n'"${ama#${root}}"
			if [ ! -f "${ama}" ]; then
				echo "./${root}: diving ${ama}..."
				cat "${ama}-ama" | ama > "${ama}"
			else
				echo "./${root}: cached ${ama}"
			fi
		done;
		echo "./${root}: writing gitignore..."
		echo "${git_ignore}" > "${1}"/.gitignore
	}
}
