#!/usr/bin/env bash
[[ `uname` == 'Darwin' ]] && { [ -d "/usr/local/opt/coreutils/libexec/gnubin" ] || { echo "gnu tools not found"; exit 1; } && PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"; }
cd "$(dirname "$0")"
cd "$(npm root | xargs dirname)"

./transform/webapp/$.sh || {
	echo "webapp failed"
	exit 1
} && ./transform/serve/$.sh 
