#!/usr/bin/env bash
DIR="$(sudo dirname "$(readlink -f "$0")")"
cd "$DIR"
cd ..

function refresh {
	git_ignore="#autogenerated by npm refresh"
	git_ignore="${git_ignore}"$'\n'".gitignore"
	find "${1}" -type f | grep "\-ama$" | sed "s/\(^.*\)-ama$/\1/" | {
		while read ama; do
			git_ignore="${git_ignore}"$'\n'"${ama#${1}}"
			if [ ! -f "${ama}" ]; then
				echo "diving for ${ama}..."
				cat "${ama}-ama" | ama > "${ama}"
			else
				echo "${ama} good"
			fi
		done;
		echo "writing gitignore..."
		echo "${git_ignore}" > "${1}"/.gitignore
	}
}

refresh deploy
